// Code generated by goderive DO NOT EDIT.

package apply

// deriveApply applies the second argument to a given function's last argument and returns a function which which takes the rest of the parameters as input and finally returns the original input function's results.
func deriveApply(f func(s string, sep string, n int) []string, n int) func(s string, sep string) []string {
	return func(s string, sep string) []string {
		return f(s, sep, n)
	}
}
