//DO NOT EDIT generated by goderive

package test

import (
	"bytes"
)

var _ = bytes.MinRead

func deriveEqualPtrToA(this, that *A) bool {
	return (this == nil && that == nil) ||
		(this != nil && that != nil) &&
			this.B == that.B &&
			((this.C == nil && that.C == nil) || (this.C != nil && that.C != nil && *this.C == *that.C)) &&
			this.D == that.D &&
			((this.E == nil && that.E == nil) || (this.E != nil && that.E != nil && *this.E == *that.E)) &&
			deriveEqualSliceOfbool(this.I, that.I) &&
			deriveEqualSliceOfPtrToB(this.J, that.J) &&
			deriveEqualSliceOfB(this.K, that.K) &&
			this.L.Equal(that.L) &&
			this.M.Equal(&that.M) &&
			deriveEqualMapOfintToB(this.N, that.N) &&
			deriveEqualMapOfstringToPtrToB(this.O, that.O) &&
			deriveEqualMapOfint64Tostring(this.P, that.P)
}
func deriveEqualPtrToB(this, that *B) bool {
	return (this == nil && that == nil) ||
		(this != nil && that != nil) &&
			bytes.Equal(this.Bytes, that.Bytes) &&
			deriveEqualMapOfintToB(this.N, that.N)
}
func deriveEqualMapOfint64Tostring(this, that map[int64]string) bool {
	if this == nil {
		if that == nil {
			return true
		} else {
			return false
		}
	} else if that == nil {
		return false
	}
	if len(this) != len(that) {
		return false
	}
	for k, v := range this {
		thatv, ok := that[k]
		if !ok {
			return false
		}
		if !(v == thatv) {
			return false
		}
	}
	return true

}
func deriveEqualSliceOfbool(this, that []bool) bool {
	if this == nil {
		if that == nil {
			return true
		} else {
			return false
		}
	} else if that == nil {
		return false
	}
	if len(this) != len(that) {
		return false
	}
	for i := 0; i < len(this); i++ {
		if !(this[i] == that[i]) {
			return false
		}
	}
	return true

}
func deriveEqualSliceOfPtrToB(this, that []*B) bool {
	if this == nil {
		if that == nil {
			return true
		} else {
			return false
		}
	} else if that == nil {
		return false
	}
	if len(this) != len(that) {
		return false
	}
	for i := 0; i < len(this); i++ {
		if !(this[i].Equal(that[i])) {
			return false
		}
	}
	return true

}
func deriveEqualSliceOfB(this, that []B) bool {
	if this == nil {
		if that == nil {
			return true
		} else {
			return false
		}
	} else if that == nil {
		return false
	}
	if len(this) != len(that) {
		return false
	}
	for i := 0; i < len(this); i++ {
		if !(this[i].Equal(&that[i])) {
			return false
		}
	}
	return true

}
func deriveEqualMapOfintToB(this, that map[int]B) bool {
	if this == nil {
		if that == nil {
			return true
		} else {
			return false
		}
	} else if that == nil {
		return false
	}
	if len(this) != len(that) {
		return false
	}
	for k, v := range this {
		thatv, ok := that[k]
		if !ok {
			return false
		}
		if !(v.Equal(&thatv)) {
			return false
		}
	}
	return true

}
func deriveEqualMapOfstringToPtrToB(this, that map[string]*B) bool {
	if this == nil {
		if that == nil {
			return true
		} else {
			return false
		}
	} else if that == nil {
		return false
	}
	if len(this) != len(that) {
		return false
	}
	for k, v := range this {
		thatv, ok := that[k]
		if !ok {
			return false
		}
		if !(v.Equal(thatv)) {
			return false
		}
	}
	return true

}
