// Code generated by goderive DO NOT EDIT.

package toerror

// deriveToError transforms sum-bool type into sum-error type. Main purpose is to make the given function composable. It returns given error when the result of the function is false.
func deriveToError(err error, f func(key string) (value string, ok bool)) func(key string) (string, error) {
	return func(key string) (string, error) {
		out0, success := f(key)
		if success {
			return out0, nil
		}
		return out0, err
	}
}
