// Code generated by goderive DO NOT EDIT.

package main

// deriveMem returns a memoized version of the input function.
func deriveMem(f func(i uint) uint) func(i uint) uint {
	m := make(map[uint]uint)
	return func(param0 uint) uint {
		if v, ok := m[param0]; ok {
			return v
		}
		v := f(param0)
		m[param0] = v
		return v
	}
}
