//  Copyright 2017 Walter Schulze
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

package main

import (
	"flag"
	"go/types"
	"io"
	"log"
	"os"
	"path/filepath"

	"github.com/kisielk/gotool"
)

func main() {
	flag.Parse()
	paths := gotool.ImportPaths(flag.Args())
	program, err := load(paths...)
	derivedFilename := "derived.gen.go"
	if err != nil {
		log.Fatal(err) // load error
	}
	for _, pkgInfo := range program.InitialPackages() {
		pkgpath := filepath.Join(filepath.Join(gotool.DefaultContext.BuildContext.GOPATH, "src"), pkgInfo.Pkg.Path())

		qual := types.RelativeTo(pkgInfo.Pkg)
		var typs []types.Type
		for i, f := range pkgInfo.Files {
			_, fname := filepath.Split(program.Fset.File(f.Pos()).Name())
			if fname == derivedFilename {
				continue
			}
			newtyps := findTypesForFuncPrefix(pkgInfo, pkgInfo.Files[i], eqFuncPrefix)
			typs = append(typs, newtyps...)
		}
		if len(typs) == 0 {
			continue
		}

		f, err := os.Create(filepath.Join(pkgpath, derivedFilename))
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		generate(f, qual, pkgInfo.Pkg.Name(), typs)
	}
}

func generate(w io.Writer, qual types.Qualifier, pkgName string, typs []types.Type) {
	p := newPrinter(w)
	p.P("//DO NOT EDIT generated by goderive")
	p.P("")
	p.P("package %s", pkgName)
	p.P("")
	p.P("import (")
	p.In()
	p.P("\"bytes\"")
	p.Out()
	p.P(")")
	p.P("")
	p.P("var _ = bytes.MinRead")
	m := newTypesMap(qual)
	for _, typ := range typs {
		m.Set(typ, false)
	}
	for _, typ := range typs {
		m.Set(typ, false)
		genEqual(p, m, qual, typ)
		m.Set(typ, true)
	}
	for _, typ := range m.List() {
		if m.Get(typ) {
			continue
		}
		genEqual(p, m, qual, typ)
		m.Set(typ, true)
	}
}
