//  Copyright 2017 Walter Schulze
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/types"
	"io"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/kisielk/gotool"
	"golang.org/x/tools/go/loader"
)

func isComparable(tt types.Type) bool {
	t := tt.Underlying()
	switch typ := t.(type) {
	case *types.Basic:
		return typ.Kind() != types.UntypedNil
	case *types.Struct:
		for i := 0; i < typ.NumFields(); i++ {
			f := typ.Field(i)
			ft := f.Type()
			if !isComparable(ft) {
				return false
			}
		}
		return true
	case *types.Array:
		return isComparable(typ.Elem())
	}
	return false
}

type p struct {
	w              io.Writer
	qual           types.Qualifier
	generatedFuncs map[string]bool
	typs           []types.Type
	indent         string
}

func (p *p) P(format string, a ...interface{}) {
	if _, err := fmt.Fprintf(p.w, p.indent+format+"\n", a...); err != nil {
		panic(err)
	}
}

func (p *p) In() {
	p.indent += "\t"
}

func (p *p) Out() {
	if len(p.indent) > 0 {
		p.indent = p.indent[1:]
	} else {
		panic("bug in code generator: unindenting more than has been indented")
	}
}

func load(paths ...string) (*loader.Program, error) {
	conf := loader.Config{
		ParserMode:  parser.ParseComments,
		AllowErrors: true,
	}
	rest, err := conf.FromArgs(paths, true)
	if err != nil {
		return nil, fmt.Errorf("could not parse arguments: %s", err)
	}
	if len(rest) > 0 {
		return nil, fmt.Errorf("unhandled extra arguments: %v", rest)
	}
	return conf.Load()
}

func main() {
	flag.Parse()
	paths := gotool.ImportPaths(flag.Args())
	program, err := load(paths...)
	derivedFilename := "derived.gen.go"
	if err != nil {
		log.Fatal(err) // load error
	}
	for _, pkgInfo := range program.InitialPackages() {
		pkgpath := filepath.Join(filepath.Join(gotool.DefaultContext.BuildContext.GOPATH, "src"), pkgInfo.Pkg.Path())

		qual := types.RelativeTo(pkgInfo.Pkg)
		var typs []types.Type
		for i, f := range pkgInfo.Files {
			_, fname := filepath.Split(program.Fset.File(f.Pos()).Name())
			if fname == derivedFilename {
				continue
			}
			newtyps := findTypesForFuncPrefix(pkgInfo, pkgInfo.Files[i], eqFuncPrefix)
			typs = append(typs, newtyps...)
		}
		if len(typs) == 0 {
			continue
		}

		f, err := os.Create(filepath.Join(pkgpath, derivedFilename))
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		generate(f, qual, pkgInfo.Pkg.Name(), typs)
	}
}

func generate(w io.Writer, qual types.Qualifier, pkgName string, typs []types.Type) {
	p := &p{
		w:              w,
		qual:           qual,
		generatedFuncs: make(map[string]bool),
		typs:           typs,
	}
	p.P("//DO NOT EDIT generated by goderive")
	p.P("")
	p.P("package %s", pkgName)
	p.P("")
	p.P("import (")
	p.In()
	p.P("\"bytes\"")
	p.Out()
	p.P(")")
	p.P("")
	p.P("var _ = bytes.MinRead")
	for _, typ := range typs {
		p.newFunc(typ)
		p.genFunc(typ)
		p.funcGenerated(typ)
	}
	for _, typ := range p.typs {
		fName := funcName(typ, p.qual)
		if p.generatedFuncs[fName] {
			continue
		}
		p.genFunc(typ)
		p.funcGenerated(typ)
	}
}

const eqFuncPrefix = "deriveEqual"

func funcName(typ types.Type, qual types.Qualifier) string {
	return eqFuncPrefix + typeName(typ, qual)
}

func (p *p) newFunc(typ types.Type) {
	fName := funcName(typ, p.qual)
	if _, ok := p.generatedFuncs[fName]; ok {
		return
	}
	p.typs = append(p.typs, typ)
	p.generatedFuncs[fName] = false
}

func (p *p) funcGenerated(typ types.Type) {
	fName := funcName(typ, p.qual)
	p.generatedFuncs[fName] = true
}

func typeName(typ types.Type, qual types.Qualifier) string {
	switch t := typ.(type) {
	case *types.Pointer:
		return "PtrTo" + typeName(t.Elem(), qual)
	case *types.Array:
		return "ArrayOf" + typeName(t.Elem(), qual)
	case *types.Slice:
		return "SliceOf" + typeName(t.Elem(), qual)
	case *types.Map:
		return "MapOf" + typeName(t.Key(), qual) + "To" + typeName(t.Elem(), qual)
	}
	return types.TypeString(typ, qual)
}

func (p *p) genFunc(typ types.Type) {
	p.funcGenerated(typ)
	typeStr := types.TypeString(typ, p.qual)
	p.P("")
	p.P("func %s(this, that %s) bool {", funcName(typ, p.qual), typeStr)
	p.In()
	switch ttyp := typ.(type) {
	case *types.Pointer:
		ref := ttyp.Elem()
		switch tttyp := ref.Underlying().(type) {
		case *types.Struct:
			numFields := tttyp.NumFields()
			if numFields == 0 {
				p.P("return (this == nil && that == nil) || (this != nil) && (that != nil)")
			} else {
				p.P("return (this == nil && that == nil) || (this != nil) && (that != nil) &&")
			}
			p.In()
			for i := 0; i < numFields; i++ {
				field := tttyp.Field(i)
				fieldType := field.Type()
				fieldName := field.Name()
				this := "this." + fieldName
				that := "that." + fieldName
				fieldStr, err := p.genField(this, that, fieldType)
				if err != nil {
					fmt.Fprintf(os.Stderr, err.Error())
					return
				}
				if (i + 1) != numFields {
					p.P(fieldStr + " &&")
				} else {
					p.P(fieldStr)
				}
			}
			p.Out()
		default:
			fmt.Fprintf(os.Stderr, "unsupported: pointer is not a named struct, but %#v\n", ref)
			return
		}
	case *types.Slice:
		p.P("if this == nil || that == nil {")
		p.In()
		p.P("return this == nil && that == nil")
		p.Out()
		p.P("}")
		p.P("if len(this) != len(that) {")
		p.In()
		p.P("return false")
		p.Out()
		p.P("}")
		p.P("for i := 0; i < len(this); i++ {")
		p.In()
		eqStr, err := p.genField("this[i]", "that[i]", ttyp.Elem())
		if err != nil {
			fmt.Fprintf(os.Stderr, err.Error())
			return
		}
		p.P("if !(%s) {", eqStr)
		p.In()
		p.P("return false")
		p.Out()
		p.P("}")
		p.Out()
		p.P("}")
		p.P("return true")
	// TODO case *types.Array:

	case *types.Map:
		p.P("if this == nil || that == nil {")
		p.In()
		p.P("return this == nil && that == nil")
		p.Out()
		p.P("}")
		p.P("if len(this) != len(that) {")
		p.In()
		p.P("return false")
		p.Out()
		p.P("}")
		p.P("for k, v := range this {")
		p.In()
		p.P("thatv, ok := that[k]")
		p.P("if !ok {")
		p.In()
		p.P("return false")
		p.Out()
		p.P("}")
		eqStr, err := p.genField("v", "thatv", ttyp.Elem())
		if err != nil {
			fmt.Fprintf(os.Stderr, err.Error())
			return
		}
		p.P("if !(%s) {", eqStr)
		p.In()
		p.P("return false")
		p.Out()
		p.P("}")
		p.Out()
		p.P("}")
		p.P("return true")
	default:
		fmt.Fprintf(os.Stderr, "unsupported type: %#v", typ)
		return
	}
	p.Out()
	p.P("}")
}

func (p *p) genField(this, that string, fieldType types.Type) (string, error) {
	if isComparable(fieldType) {
		return fmt.Sprintf("%s == %s", this, that), nil
	}
	switch typ := fieldType.(type) {
	case *types.Pointer:
		ref := typ.Elem()
		if _, ok := ref.(*types.Named); ok {
			return fmt.Sprintf("%s.Equal(%s)", this, that), nil
		}
		eqStr, err := p.genField("*"+this, "*"+that, ref)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("((%[1]s == nil && %[2]s == nil) || (%[1]s != nil && %[2]s != nil && %[3]s))", this, that, eqStr), nil
	// TODO case *types.Array:
	// 	p.newFunc(typ)
	// 	return fmt.Sprintf("%s(%s, %s)", funcName(typ, p.qual), this, that), nil
	case *types.Slice:
		if b, ok := typ.Elem().(*types.Basic); ok && b.Kind() == types.Byte {
			return fmt.Sprintf("bytes.Equal(%s, %s)", this, that), nil
		}
		p.newFunc(typ)
		return fmt.Sprintf("%s(%s, %s)", funcName(typ, p.qual), this, that), nil
	case *types.Map:
		p.newFunc(typ)
		return fmt.Sprintf("%s(%s, %s)", funcName(typ, p.qual), this, that), nil
	case *types.Named:
		return fmt.Sprintf("%s.Equal(&%s)", this, that), nil
	default: // *Chan, *Tuple, *Signature, *Interface, *types.Basic.Kind() == types.UntypedNil, *Struct
		return "", fmt.Errorf("unsupported type %#v", fieldType)
	}
}

type findTypes struct {
	pkgInfo    *loader.PackageInfo
	funcPrefix string
	typs       []types.Type
}

func (this *findTypes) Visit(node ast.Node) (w ast.Visitor) {
	call, ok := node.(*ast.CallExpr)
	if !ok {
		return this
	}
	fn, ok := call.Fun.(*ast.Ident)
	if !ok {
		return this
	}
	if !strings.HasPrefix(fn.Name, this.funcPrefix) {
		return this
	}
	if len(call.Args) != 2 {
		fmt.Fprintf(os.Stderr, "%s does not have two arguments\n", fn.Name)
		return this
	}
	t0 := this.pkgInfo.TypeOf(call.Args[0])
	t1 := this.pkgInfo.TypeOf(call.Args[1])
	if !types.Identical(t0, t1) {
		fmt.Fprintf(os.Stderr, "%s has two arguments, but they are of different types %s != %s\n",
			fn.Name, t0, t1)
		return this
	}
	name := strings.TrimPrefix(fn.Name, this.funcPrefix)
	qual := types.RelativeTo(this.pkgInfo.Pkg)
	typeStr := typeName(t0, qual)
	if typeStr != name {
		//TODO think about whether this is really necessary
		fmt.Fprintf(os.Stderr, "%s's suffix %s does not match the type %s\n",
			fn.Name, name, typeStr)
		return this
	}
	this.typs = append(this.typs, t0)
	return this
}

func findTypesForFuncPrefix(pkgInfo *loader.PackageInfo, f *ast.File, funcPrefix string) []types.Type {
	var typs []types.Type
	for _, d := range f.Decls {
		finder := &findTypes{pkgInfo, funcPrefix, nil}
		ast.Walk(finder, d)
		typs = append(typs, finder.typs...)
	}
	return typs
}
