//  Copyright 2017 Walter Schulze
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"io"
)

type Printer interface {
	P(format string, a ...interface{})
	In()
	Out()
	Flush(pkgName string, w io.Writer) error
}

type printer struct {
	w      *bytes.Buffer
	indent string
}

func newPrinter() Printer {
	return &printer{bytes.NewBuffer(nil), ""}
}

func (p *printer) P(format string, a ...interface{}) {
	fmt.Fprintf(p.w, p.indent+format+"\n", a...)
}

func (p *printer) In() {
	p.indent += "\t"
}

func (p *printer) Out() {
	if len(p.indent) > 0 {
		p.indent = p.indent[1:]
	} else {
		panic("bug in code generator: unindenting more than has been indented")
	}
}

func (p *printer) Flush(pkgName string, file io.Writer) error {
	top := bytes.NewBuffer(nil)
	top.WriteString("//DO NOT EDIT generated by goderive\n")
	top.WriteString("\n")
	top.WriteString("package " + pkgName + "\n")
	top.WriteString("\n")
	top.WriteString("import (\n")
	top.WriteString("\t\"bytes\"\n")
	top.WriteString(")\n")
	top.WriteString("\n")
	top.WriteString("var _ = bytes.MinRead\n")
	_, err := top.WriteTo(file)
	if err != nil {
		return err
	}
	_, err = p.w.WriteTo(file)
	return err
}
