// Code generated by goderive DO NOT EDIT.

package package2

func deriveEqual(this, that *Type2) bool {
	return (this == nil && that == nil) ||
		this != nil && that != nil &&
			this.Field1.Equal(that.Field1)
}
