// Code generated by goderive DO NOT EDIT.

package package1

// deriveEqual returns whether this and that are equal.
func deriveEqual(this, that *Type1) bool {
	return (this == nil && that == nil) ||
		this != nil && that != nil &&
			((this.StringPtr == nil && that.StringPtr == nil) || (this.StringPtr != nil && that.StringPtr != nil && *(this.StringPtr) == *(that.StringPtr)))
}
