// Code generated by goderive DO NOT EDIT.

package main

// Min returns the minimum of the two input values.
func Min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

// Min_ returns the minimum of the two input values.
func Min_(a, b uint) uint {
	if a < b {
		return a
	}
	return b
}
