// Code generated by goderive DO NOT EDIT.

package main

import (
	"regexp"
)

// deriveMem returns a memoized version of the input function.
func deriveMem(f func(r string) *regexp.Regexp) func(r string) *regexp.Regexp {
	m := make(map[string]*regexp.Regexp)
	return func(param0 string) *regexp.Regexp {
		if v, ok := m[param0]; ok {
			return v
		}
		v := f(param0)
		m[param0] = v
		return v
	}
}
