//DO NOT EDIT generated by goderive

package gogenerate

func deriveEqualPtrToMyStruct(this, that *MyStruct) bool {
	return (this == nil && that == nil) || (this != nil) && (that != nil) &&
		this.Int64 == that.Int64 &&
		this.String == that.String
}
