// Code generated by goderive DO NOT EDIT.

package gogenerate

func deriveEqual(this, that *MyStruct) bool {
	return (this == nil && that == nil) || this != nil && that != nil && deriveEqualMyStruct(*this, *that)
}

func deriveEqualMyStruct(this, that MyStruct) bool {
	return this.Int64 == that.Int64 &&
		this.String == that.String
}
