// Code generated by goderive DO NOT EDIT.

package set

// deriveSet returns the input list as a map with the items of the list as the keys of the map.
//
// Deprecated: In favour of generics.
func deriveSet(list []int) map[int]struct{} {
	set := make(map[int]struct{}, len(list))
	for _, v := range list {
		set[v] = struct{}{}
	}
	return set
}
