// Code generated by goderive DO NOT EDIT.

package main

import (
	"sort"
)

// Sort sorts the slice inplace and also returns it.
func Sort(list []string) []string {
	sort.Strings(list)
	return list
}

// Keys returns the keys of the input map as a slice.
func Keys(m map[string]Person) []string {
	keys := make([]string, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	return keys
}
