// Code generated by goderive DO NOT EDIT.

package copyto

func deriveCopyTo(this, that *MyStruct) {
	that.Int64 = this.Int64
	if this.StringPtr == nil {
		that.StringPtr = nil
	} else {
		that.StringPtr = new(string)
		*that.StringPtr = *this.StringPtr
	}
}
