// Code generated by goderive DO NOT EDIT.

package keys

import (
	"sort"
)

func deriveSort(list []string) []string {
	sort.Strings(list)
	return list
}

func deriveKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for key, _ := range m {
		keys = append(keys, key)
	}
	return keys
}
