name: Go

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x

      - name: Gofmt
        run: make gofmt

      - name: Test
        run: make test

      - name: Vet
        run: |
          go vet ./derive/...
          go vet ./example/...
          go vet ./plugin/...
          go vet ./test/normal/...

      - name: Diff
        run: git diff --exit-code .
